name: Pulling_all_trips_data_from_cartrack

on:
  schedule:
    - cron: "01 23 * * *"
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install datetime

    - name: Run script
      run: python Pulling_all_trips_data_from_cartrack.py
